name: cam-httpflv-build
on:
  push:
    paths:
      - 'server.py'
      - 'tool.py'
      - 'Dockerfile'
      - 'config.json'
      - 'requirements.txt'
      - 'utils/**'

env:
  TZ: Asia/Shanghai
  IMAGE_NAME: cam-httpflv


jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=today::$(date +'%Y-%m-%d')"
          echo  $(date)

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKHUB_USER }}
          password: ${{ secrets.DOCKHUB_SECRET }}

      - name: Build and Push to DockerHUB
        uses: docker/build-push-action@master
        with:
          platforms: linux/amd64,linux/arm64
          context: ./
          file: ./Dockerfile
          push: true
          tags: zhoukunpeng505/${{ steps.vars.outputs.image_name }}:${{ steps.date.outputs.today }}-${{ steps.vars.outputs.sha_short }},zhoukunpeng505/${{ steps.vars.outputs.image_name }}:latest




